Leaderboard: Project setup branch
abenezer-addisu/Leaderboard_01 pull request #1
Opened 2023-05-24 14:51 UTC by abenezer-addisu

In This Branch :

- [ ]  we use Gitflow.
- [ ] we Create npm project with webpack. 
- [ ] we Write plain HTML markup with minimum styling

2023-05-24 15:18 UTC, Zuhaib042 reviewed
Hi @abenezer-addisu 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a readme file in the repo. kindly consider adding a readme file and fill all the sections with relevant information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-24 17:39 UTC, Ibizugbe requested changes
Hi @abenezer-addisu 👋👋, 

![tryagain](https://github.com/abenezer-addisu/Leaderboard_01/assets/64643995/0e011807-7d4e-4064-b1e2-4bbaf68a0243)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are currently setup and they are passing👍.
- [x] Gitflow have been properly used👍.
- [x]  `node_modules` folder have been added to `.gitignore`👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 17:39 UTC, Ibizugbe commented on package.json
> +    "build": "webpack"
Currently, I think you don't have any script to run or start your server. hence, it is not possible to run your project on a server🥲. Kindly add the necessary script to make it possible to run your project on the server and ensure it is possible to run your project on a local server👍.

2023-05-25 10:00 UTC, LionRouge1 approved these changes
Hi @abenezer-addisu, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-05-25 21:14 UTC, merged